### ISSUE TITLE
Add sound effect

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/nafas#4]

**Comment by sepandhaghighi** [comment]
@sadrasabouri Do you have any interest to handle this issue?

**Comment by sadrasabouri** [comment]
Yes, I'll handle it soon.

**Comment by sepandhaghighi** [comment]
@sadrasabouri Do you have any plan for this issue ?
Take a look at [this link](https://stackoverflow.com/questions/59042397/play-sound-asynchronously-in-python)
