### ISSUE TITLE
Add new sound for preparing section

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/nafas#43]
#### Description
Add new sound for preparing section

#### Operating System
Windows 10
#### Python Version
Python 3.5.2
#### Nafas Version (Use : `nafas.__version__`)
v0.3

**Comment by sepandhaghighi** [comment]
@sadrasabouri Could you please process this request?

**Comment by sadrasabouri** [comment]
OK.
You mean new sounds for each section which will be played randomly?

**Comment by sepandhaghighi** [comment]
> OK.
> You mean new sounds for each section which will be played randomly?

No, adding a new soundtrack for the `preparing` section

**Comment by sadrasabouri** [comment]
I'm going to change other sections speaker too.
`US English / Joanna` will be our next speaker. (Later one was `US English / Justin`)
